src/Core/Planeacion/AdminBundle/Entity/Materia.php
<?php
namespace Core\Planeacion\AdminBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints as DocAssert;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Materia
 *
 * @ORM\Table(name="materia")
 * @ORM\HasLifecycleCallbacks()
 * @DocAssert\UniqueEntity(fields={"clave","planEstudio"}, message="Ya existe una materia con esa clave en ese plan de estudio.")
 * @ORM\Entity(repositoryClass="Core\Planeacion\AdminBundle\Repository\MateriaRepository")
 */
class Materia
{
    /**
     * @var float
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\SequenceGenerator(sequenceName="materia_id_seq", allocationSize=1, initialValue=1)
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=100, nullable=false)
     */
    private $nombre;

    /**
     * @var string
     *
     * @ORM\Column(name="clave", type="string", length=10,nullable=false)
     */
    private $clave;

    /**
     * @var integer
     *
     * @ORM\Column(name="frecuencia_semanal", type="integer", nullable=true)
     */
    private $frecuenciaSemanal;

    /**
     * @var boolean
     *
     * @ORM\Column(name="activo", type="boolean", nullable=false, options={"default" = 1})
     */
    private $activo;


    /**
     * @var \Semestre
     *
     * @ORM\ManyToOne(targetEntity="Semestre")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="semestre", referencedColumnName="id")
     * })
     */
    private $semestre;
    /**
     * @var \PlanEstudio
     *
     * @ORM\ManyToOne(targetEntity="PlanEstudio",inversedBy="materias")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="plan_estudio", referencedColumnName="id")
     * })
     */
    private $planEstudio;
    /**
     * @var \TipoMateria
     *
     * @ORM\ManyToOne(targetEntity="TipoMateria")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="tipo_materia", referencedColumnName="id", nullable=false)
     * })
     */
    private $tipoMateria;

    /**
     * @var \ProfePeriodo
     *
     * @ORM\ManyToMany(targetEntity="ProfePeriodo",mappedBy="materia", cascade={"persist","remove"})
     */
    private $profePeriodo;
    /**
     * @var \ProfePeriodo
     *
     * @ORM\ManyToMany(targetEntity="ProfePeriodo",mappedBy="historicoMateriaManual", cascade={"persist","remove"})
     */
    private $profePeriodoManual;
    /**
     * @var \PreferenciaProfeMateria
     *
     * @ORM\OneToMany(targetEntity="PreferenciaProfeMateria",mappedBy="materia", cascade={"persist","remove"})
     */
    private $preferenciaProfeMateria;

    /**
     * @var \PreferenciaProfeMateria
     *
     * @ORM\OneToMany(targetEntity="ProfePeriodoHorario",mappedBy="materia", cascade={"persist","remove"})
     */
    private $profePeriodoHorario;
    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function events()
    {
        if($this->getSemestre() == null && $this->getTipoMateria()->getId() == 1 && $this->getActivo() == true)
            throw new Exception('Error');
        $this->nombre=strtoupper($this->nombre);
    }
    public function getTextoSinCarrera()
    {
        return $this->getClave().'-'.$this->getNombre();
    }
    public function getTexto()
    {
        if($this->getPlanEstudio() != null) {
            return $this->getClave() . '-' . $this->getNombre() . '-' . $this->getCarrera();
        }
        else
            return $this->getClave() . '-' . $this->getNombre() ;
    }
    public function getTextoConSemestre()
    {
        if($this->getPlanEstudio() != null) {
            if ($this->getSemestre())
                return $this->getClave() . '-' . $this->getNombre() . '-' . $this->getCarrera() . '/Sem:' . $this->getSemestre()->getNombre();
            else
                return $this->getClave() . '-' . $this->getNombre() . '-' . $this->getCarrera();
        }
        else{
            if ($this->getSemestre())
                return $this->getClave() . '-' . $this->getNombre();
            else
                return $this->getClave() . '-' . $this->getNombre();
        }
    }
    public function getCarrera()
    {
        return substr(ucfirst($this->getPlanEstudio()->getCarrera()->getNombre()),0,1);
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->activo=true;
        $this->profePeriodo=new ArrayCollection();
        $this->profePeriodoManual=new ArrayCollection();
        $this->preferenciaProfeMateria=new ArrayCollection();
    }
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return Materia
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    
        return $this;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set clave
     *
     * @param string $clave
     * @return Materia
     */
    public function setClave($clave)
    {
        $this->clave = $clave;
    
        return $this;
    }

    /**
     * Get clave
     *
     * @return string 
     */
    public function getClave()
    {
        return $this->clave;
    }

    /**
     * Set frecuenciaSemanal
     *
     * @param integer $frecuenciaSemanal
     * @return Materia
     */
    public function setFrecuenciaSemanal($frecuenciaSemanal)
    {
        $this->frecuenciaSemanal = $frecuenciaSemanal;
    
        return $this;
    }

    /**
     * Get frecuenciaSemanal
     *
     * @return integer 
     */
    public function getFrecuenciaSemanal()
    {
        return $this->frecuenciaSemanal;
    }

    /**
     * Set activo
     *
     * @param boolean $activo
     * @return Materia
     */
    public function setActivo($activo)
    {
        $this->activo = $activo;
    
        return $this;
    }

    /**
     * Get activo
     *
     * @return boolean 
     */
    public function getActivo()
    {
        return $this->activo;
    }


    /**
     * Set semestre
     *
     * @param \Core\Planeacion\AdminBundle\Entity\Semestre $semestre
     * @return Materia
     */
    public function setSemestre(\Core\Planeacion\AdminBundle\Entity\Semestre $semestre = null)
    {
        $this->semestre = $semestre;
    
        return $this;
    }

    /**
     * Get semestre
     *
     * @return \Core\Planeacion\AdminBundle\Entity\Semestre 
     */
    public function getSemestre()
    {
        return $this->semestre;
    }


    /**
     * Set planEstudio
     *
     * @param \Core\Planeacion\AdminBundle\Entity\PlanEstudio $planEstudio
     * @return Materia
     */
    public function setPlanEstudio(\Core\Planeacion\AdminBundle\Entity\PlanEstudio $planEstudio = null)
    {
        $this->planEstudio = $planEstudio;

        return $this;
    }

    /**
     * Get planEstudio
     *
     * @return \Core\Planeacion\AdminBundle\Entity\PlanEstudio
     */
    public function getPlanEstudio()
    {
        return $this->planEstudio;
    }

    /**
     * @var boolean
     *
     * @ORM\Column(name="horas_extra", type="boolean", nullable=false, options={"default"=0})
     */
    private $horasextra;

    /**
     * Add profePeriodo
     *
     * @param \Core\Planeacion\AdminBundle\Entity\ProfePeriodo $profePeriodo
     * @return Materia
     */
    public function addProfePeriodo(\Core\Planeacion\AdminBundle\Entity\ProfePeriodo $profePeriodo)
    {
        $profePeriodo->addMateria($this);
        $this->profePeriodo[] = $profePeriodo;
    
        return $this;
    }

    /**
     * Remove profePeriodo
     *
     * @param \Core\Planeacion\AdminBundle\Entity\ProfePeriodo $profePeriodo
     */
    public function removeProfePeriodo(\Core\Planeacion\AdminBundle\Entity\ProfePeriodo $profePeriodo)
    {
        $profePeriodo->removeMateria($this);
        $this->profePeriodo->removeElement($profePeriodo);
    }

    /**
     * Get profePeriodo
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getProfePeriodo()
    {
        return $this->profePeriodo;
    }

    /**
     * Add profePeriodoManual
     *
     * @param \Core\Planeacion\AdminBundle\Entity\ProfePeriodo $profePeriodoManual
     * @return Materia
     */
    public function addProfePeriodoManual(\Core\Planeacion\AdminBundle\Entity\ProfePeriodo $profePeriodoManual)
    {
        $profePeriodoManual->addHistoricoMateriaManual($this);
        $this->profePeriodoManual[] = $profePeriodoManual;
    
        return $this;
    }

    /**
     * Remove profePeriodoManual
     *
     * @param \Core\Planeacion\AdminBundle\Entity\ProfePeriodo $profePeriodoManual
     */
    public function removeProfePeriodoManual(\Core\Planeacion\AdminBundle\Entity\ProfePeriodo $profePeriodoManual)
    {
        $this->profePeriodoManual->removeElement($profePeriodoManual);
    }

    /**
     * Get profePeriodoManual
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getProfePeriodoManual()
    {
        return $this->profePeriodoManual;
    }

    /**
     * Set tipoMateria
     *
     * @param \Core\Planeacion\AdminBundle\Entity\TipoMateria $tipoMateria
     * @return Materia
     */
    public function setTipoMateria(\Core\Planeacion\AdminBundle\Entity\TipoMateria $tipoMateria = null)
    {
        $this->tipoMateria = $tipoMateria;
    
        return $this;
    }

    /**
     * Get tipoMateria
     *
     * @return \Core\Planeacion\AdminBundle\Entity\TipoMateria 
     */
    public function getTipoMateria()
    {
        return $this->tipoMateria;
    }

    /**
     * Set horasextra
     *
     * @param boolean $horasextra

src/Core/Planeacion/AdminBundle/Entity/Periodo.php
<?php
namespace Core\Planeacion\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints as DocAssert;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Periodo
 *
 * @ORM\Table(name="periodo")
 * @ORM\HasLifecycleCallbacks()
 * @DocAssert\UniqueEntity(fields={"anno","tipoPeriodo"}, message="Ya existe ese período en ese año.")
 * @ORM\Entity(repositoryClass="Core\Planeacion\AdminBundle\Repository\PeriodoRepository")
 */
class Periodo
{
    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\SequenceGenerator(sequenceName="periodo_id_seq", allocationSize=1, initialValue=1)
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="anno", type="integer",  nullable=true)
     */
    private $anno;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=50, nullable=true)
     */
    private $nombre;

    /**
     * @var \ProfePeriodo
     *
     * @ORM\OneToMany(targetEntity="ProfePeriodo",mappedBy="periodo")
     */
    private $profePeriodo;

    /**
     * @var \DescargaAdministrativa
     *
     * @ORM\OneToMany(targetEntity="DescargaAdministrativa",mappedBy="periodo")
     */
    private $descarga;
    /**
     * @var \TipoPeriodo
     *
     * @ORM\ManyToOne(targetEntity="TipoPeriodo")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="tipo_periodo", referencedColumnName="id")
     * })
     */
    private $tipoPeriodo;

    /**
     * @var \ProfePeriodoHorario
     *
     * @ORM\OneToOne(targetEntity="Core\Planeacion\AdminBundle\Entity\Anteproyecto",mappedBy="periodo")
     */
    private $anteproyecto;


    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function events()
    {
        $this->nombre =  $this->getTipoPeriodo()->getNombre().'/'.$this->getAnno();
    }
    public function getAbreviado()
    {
        return $this->getTipoPeriodo()->getId().'/'.$this->getAnno();
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set anno
     *
     * @param string $anno
     * @return Periodo
     */
    public function setAnno($anno)
    {
        $this->anno = $anno;
    
        return $this;
    }

    /**
     * Get anno
     *
     * @return string 
     */
    public function getAnno()
    {
        return $this->anno;
    }
    /**
     * Set tipoPeriodo
     *
     * @param \Core\Planeacion\AdminBundle\Entity\TipoPeriodo $tipoPeriodo
     * @return Periodo
     */
    public function setTipoPeriodo(\Core\Planeacion\AdminBundle\Entity\TipoPeriodo $tipoPeriodo = null)
    {
        $this->tipoPeriodo = $tipoPeriodo;
    
        return $this;
    }

    /**
     * Get tipoPeriodo
     *
     * @return \Core\Planeacion\AdminBundle\Entity\TipoPeriodo 
     */
    public function getTipoPeriodo()
    {
        return $this->tipoPeriodo;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return Periodo
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    
        return $this;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
      //  $em = new EntityManager();

        $this->profePeriodo = new \Doctrine\Common\Collections\ArrayCollection();
        $this->descarga = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Add profePeriodo
     *
     * @param \Core\Planeacion\AdminBundle\Entity\ProfePeriodo $profePeriodo
     * @return Periodo
     */
    public function addProfePeriodo(\Core\Planeacion\AdminBundle\Entity\ProfePeriodo $profePeriodo)
    {
        $this->profePeriodo[] = $profePeriodo;
    
        return $this;
    }

    /**
     * Remove profePeriodo
     *
     * @param \Core\Planeacion\AdminBundle\Entity\ProfePeriodo $profePeriodo
     */
    public function removeProfePeriodo(\Core\Planeacion\AdminBundle\Entity\ProfePeriodo $profePeriodo)
    {
        $this->profePeriodo->removeElement($profePeriodo);
    }

    /**
     * Get profePeriodo
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getProfePeriodo()
    {
        return $this->profePeriodo;
    }

    /**
     * Add descarga
     *
     * @param \Core\Planeacion\AdminBundle\Entity\DescargaAdministrativa $descarga
     * @return DescargaAdministrativa
     */
    public function addDescarga(\Core\Planeacion\AdminBundle\Entity\DescargaAdministrativa $descarga)
    {
        $this->descarga[] = $descarga;

        return $this;
    }

    /**
     * Remove Descarga
     *
     * @param \Core\Planeacion\AdminBundle\Entity\DescargaAdministrativa $descarga
     */
    public function removeDescarga(\Core\Planeacion\AdminBundle\Entity\DescargaAdministrativa $descarga)
    {
        $this->descarga->removeElement($descarga);
    }

    /**
     * Get descarga
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getDescarga()
    {
        return $this->descarga;
    }

    public function __toString(){
        return $this->getAbreviado();
    }
}

src/Core/Planeacion/AdminBundle/Resources/views/Profesor/edit.html.twig
{% extends 'PlaneacionAdminBundle:Profesor:new.html.twig' %}
{% block titulo %}
        Editar profesor: <b>{{ obj.nombre }}-{{ obj.numeroEmpleado }}</b>
{% endblock %}
{% block urlForm %}{{ path(model.rutas.edit) }}{% endblock %}
{% block form_fields %}<input type="hidden" name="id" value="{{ app.request.get('id') }}"/>{% endblock %}

src/Core/Planeacion/AdminBundle/Resources/views/Profesor/header.html.twig
<div class="radio-list">
    <label class="radio-inline" style="padding-left: 0px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <p class="form-control-inline chekador"  style="margin-left: 10px" val="1"  > (1)</p>
    </label>
    <label class="radio-inline" style="margin-left: 2px;padding-left: 2px">
        <p class="form-control-inline chekador"  style="margin-left: 10px"  val="2"> (2)</p>
    </label>
    <a href="javascript:;" class="radio_cleaner" style="visibility: hidden"><i class="fa fa-times"></i></a>
</div>

src/Core/Planeacion/AdminBundle/Resources/views/Profesor/profe_detail.twig
<div class="row form-group ">
   <div class="pull-left" style="padding-left: 15px;">
     <button class="btn btn-sm blue "><i class="fa fa-print"></i> Imprimir</button>
   </div>
</div>
<div class="row form-group">
<div class="col-md-12">
<div class="col-md-12 well">
<div class="col-md-4 text-left">
    <div class="span4">
            <h4><strong>Detalles del profesor</strong></h4>
            <br> <br>
            {% if datosS['Foto'] is not null %}
                 {{ datosS['Foto'] | raw }}
                    <br> <br>
            {% endif %}

             {% if datosS['Nombre'] is not null %}
                    <strong>Nombres y Apellidos:</strong>
                    {{datosS['Nombre']}} <br>
            {% endif %}

            {% if datosS['Fecha de nacimiento'] is not null %}
                 <strong>Fecha de nacimiento: </strong> 
                {{datosS['Fecha de nacimiento']}} <br>
            {% endif %}
                          
            <address>
                {% if datosS['Domicilio'] is not null %}
                     <strong>Domicilio: </strong><br>
                     {{datosS['Domicilio']}} <br>
                {% endif %}
            </address>
                                   
            <address>
                {% if datosS['Correo'] is not null %}
                  <strong>Correo electronico: </strong>
                  <a href="mailto:#">{{datosS['Correo']}}</a><br>
                {% endif %}

                {% if datosS['Facebook'] is not null %}
                  <strong>Facebook: </strong>
                  <a href="#">{{datosS['Facebook']}}</a>
                {% endif %}
            </address>
                             
            {% if datosS['Teléfono particular'] is not null %}
                <abbr title="Teléfono">Teléfono:</abbr> {{datosS['Teléfono particular']}}<br>
            {% endif %}
            
            {% if datosS['Teléfono celular'] is not null %}
                <abbr title="Teléfono">Celular:</abbr> {{datosS['Teléfono celular']}}<br>
                <br>
            {% endif %}
        </div>
</div>


<div class="col-md-4 text-left">
<div class="span4">
    <div class="">
        <h4><strong></strong></h4>
            <br> <br>
                <address>
                    {% if datosS['Fecha ingreso Universidad'] is not null %}
                    <strong>Fecha ingreso Universidad: </strong> {{datosS['Fecha ingreso Universidad']}}<br>
                    {% endif %}

                    {% if datosS['Fecha ingreso Facultad'] is not null %}
                    <strong>Fecha ingreso Facultad: </strong> {{datosS['Fecha ingreso Facultad']}}<br>
                    {% endif %}
                </address>

                <address>
                    {% if datosS['Carrera'] is not null %}
                    <strong>Carrera: </strong> {{datosS['Carrera']}}<br>
                    {% endif %}
                     {% if datosS['numeroEmpleado'] is not null %}
                    <strong>ID Empleado: </strong> {{datosS['numeroEmpleado']}}<br>
                    {% endif %}
                </address>  
                <address>
                    {% if datosS['Lugar donde labora'] is not null %}
                    <strong>Lugar donde labora: </strong> {{datosS['Lugar donde labora']}}<br>
                    {% endif %}

                    {% if datosS['Dirección donde labora'] is not null %}
                    <strong>Dirección donde labora: </strong> {{datosS['Dirección donde labora']}}<br>
                    {% endif %}

                    {% if datosS['Teléfono donde labora'] is not null %}
                    <strong>Teléfono donde labora: </strong> {{datosS['Teléfono donde labora']}}<br>
                    {% endif %}
                </address>
    </div>
 </div>
 </div>


<div class="col-md-4 text-left">
<div class="span4">
    <div class="">
        <h4><strong></strong></h4>
            <br> <br>
                <address>
                <tr>
                    <td  class="text-left">
                        <b> Materias de preferencia </b>
                    </td>
                    <td class="text-left">
                        {% for materia in materias  %}
                            <div style="margin-bottom:2px">
                                {{ loop.index }})  {{ materia.texto }}
                            </div>
                        {% endfor %}
                    </td>
                </tr>


                {% if datosC['horas1'] is defined or datosC['horas3'] is defined %}
                 <br> <br>
                <tr>
                    <td  class="text-left">
                        <b> Horas de preferencia 1 </b>
                    </td>
                    <td class="text-left" >
                        {% if datosC['horas1'] is defined %}
                        <b> Lunes a Viernes</b>
                        {% for preferencia in datosC['horas1']  %}
                            <div style="margin-bottom:2px">
                                {{ loop.index }}) {{ preferencia.hora.nombre }}
                            </div>
                        {% endfor %}
                        <br>
                        {% endif %}
                        {% if datosC['horas3'] is defined %}
                        <b>S&aacute;bado</b>
                        {% for preferencia in datosC['horas3']  %}
                            <div style="margin-bottom:2px">
                                {{ loop.index }}) {{ preferencia.hora.nombre }}
                            </div>

                        {% endfor %}
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
                       {% if datosC['horas2'] is defined or datosC['horas4'] is defined %}
                        <br> <br>
                <tr>
                    <td  class="text-left">
                        <b> Horas de preferencia 2</b>
                    </td>
                    <td class="text-left" >
                        {% if datosC['horas2'] is defined %}
                        <b> Lunes a Viernes</b>
                        {% for preferencia in datosC['horas2']  %}
                            <div style="margin-bottom:2px">
                                {{ loop.index }}) {{ preferencia.hora.nombre }}
                            </div>
                        {% endfor %}
                        <br>
                        {% endif %}
                        {% if datosC['horas4'] is defined %}
                        <b> S&aacute;bado</b>
                        {% for preferencia in datosC['horas4']  %}
                            <div style="margin-bottom:2px">
                                {{ loop.index }}) {{ preferencia.hora.nombre }}
                            </div>
                        {% endfor %}
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
                </address>

                <address>
                    {% if datosS['Habilidades y competencias'] is not null %}
                    <strong>Habilidades y competencias: </strong> {{datosS['Habilidades y competencias']}}<br>
                    {% endif %}
                     {% if datosS['Idiomas'] is not null %}
                    <strong>Idiomas: </strong> {{datosS['Idiomas']}}<br>
                    {% endif %}
                </address>  
             
    </div>
 </div>
 </div>

 </div></div>

                   

                            </div>
                        </div>
                            </div>
                        </div>

 </div>

src/Core/Planeacion/AdminBundle/Resources/views/Profesor/registroMateriasTable.html.twig
<div class="form-group">
    <div class="table-responsive col-md-6">
        <table class="table  table-bordered ">
            <thead >
                <tr style="vertical-align: middle">
                    <th width="5%" class="text-center"> <span> Per&iacute;odo </span></th>  <th width="40%" class="text-center"><span> Materia </span></th>
                    {% if hayBorrable == true%}
                        <th width="1%"></th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {% for EPPeriodo in historial[lastP:] if printedM <= divisionTabla %}
                {% set lastM = 0 %}
                {% for materia in EPPeriodo.materia[lastM:] if printedM <= divisionTabla %}
                    <tr style="vertical-align: middle" >

                        <td class="text-center" style="vertical-align: middle">
                            <span> {{ EPPeriodo.periodo.abreviado }}</span>
                        </td>
                        <td class="text-left"  style="vertical-align: middle">
                                <span> {{ materia.materia.texto }}</span>
                        </td>
                        {% if hayBorrable == true%}
                            <td>
                                {% if materia.borrable %}
                                    <a  class=" red ajaxify" type="json" block="form_block" target="#ajax_form_container_registro_materias" href="{{ path("planeacion_admin_crud_profesor_eliminar_registro_materias") }}?idProfe={{ profe.id }}&idMateria={{ materia.materia.id }}&periodo={{ EPPeriodo.periodo.id }}"  style="background-color: #d84a38;margin: 0px; padding-left: 5px; padding-right: 5px; cursor: pointer; vertical-align: middle"><i class="fa fa-times " style=" color: #ffffff"></i></a>
                                {% endif %}
                            </td>
                        {% endif %}
                    </tr>
                    {% set printedM = printedM+1 %}
                    {% set lastM = lastM+1 %}
                {% endfor %}
                {% set lastP = lastP+1 %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

src/Core/Planeacion/AdminBundle/Resources/views/Profesor/seleccion_materias.html.twig
<div class="seleccion_materias row" >
        <div class=" col-md-12">
            <div class="tabbable tabbable-custom boxless tabbable-reversed">
                <ul class="nav nav-tabs">
                    {% for EPCarrera in array %}
                        <li class="{% if loop.first %}active{% endif %}">
                            <a href="#seleccion_materias_tab_{{ EPCarrera.carrera.id }}"  data-toggle="tab">
                                {{ EPCarrera.carrera.nombre }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
                <div class="tab-content">
                    {% for EPCarrera in array %}
                        <div class="tab-pane {% if loop.first %}active{% endif %}" id="seleccion_materias_tab_{{ EPCarrera.carrera.id }}" >
                            {{ include ("@PlaneacionAdmin/Profesor/seleccion_materias_tab.html.twig") }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row ">
            <a href="javascript:;" class="pull-right materias_seleccion_limpiador_btn btn btn-sm red "><i class="fa fa-times"></i>Limpiar preferencias de materias.</a>
        </div>
</div>